name: Pinger Service

on:
  schedule:
    # Runs every 10 minutes (update this to match your config.json pingInterval)
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run ping script
        run: node ping.js
        env:
            SB_TOKEN: ${{ secrets.SB_API_TOKEN }}
        #   LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        #   LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        #   AUTH_KEY: ${{ secrets.AUTH_KEY }}

